// Build scripts/seed.sql (INSERT OR REPLACE) from every data/tests/*.json.
// Then run it with:  cfl d1 execute us-bme-test-db --file scripts/seed.sql [--remote] --acc rugan
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { validateTest } from "../src/validate.js";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, "..");
const dir = join(root, "data", "tests");
const out = join(root, "scripts", "seed.sql");

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

const files = readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
// Curated + sample tests are managed by this seed; AI-generated ones are left alone.
const lines = ["-- Auto-generated by scripts/seed.mjs", "DELETE FROM tests WHERE source IN ('curated','sample');"];
let n = 0, bad = 0;

for (const f of files) {
  const test = JSON.parse(readFileSync(join(dir, f), "utf8"));
  const v = validateTest(test);
  if (!v.ok) { console.error(`SKIP ${f}: ${v.errors[0]}`); bad++; continue; }
  const source = test.source === "sample" ? "sample" : "curated"; // preserve PDF-imported samples
  test.source = source;
  const qc = test.questions.length;
  const createdAt = test.createdAt || "2026-06-02T00:00:00.000Z";
  lines.push(
    `INSERT OR REPLACE INTO tests (id, grade, subject, test_type, title, time_limit_minutes, question_count, source, created_at, data) VALUES (` +
    `${q(test.id)}, ${test.grade}, ${q(test.subject)}, ${q(test.testType)}, ${q(test.title)}, ` +
    `${test.timeLimitMinutes}, ${qc}, ${q(source)}, ${q(createdAt)}, ${q(JSON.stringify(test))});`
  );
  n++;
}

writeFileSync(out, lines.join("\n") + "\n");
console.log(`Wrote ${out} with ${n} tests${bad ? ` (${bad} skipped)` : ""}.`);
console.log(`Run:  cfl d1 execute us-bme-test-db --remote --file scripts/seed.sql --acc rugan`);
